In [1]:
import numpy as np

In [2]:
class NeuralNet:
  def __init__(self, input_nodes):
    self.n = input_nodes
    self.w = np.zeros((self.n))
    self.b = 0

  def __train(self, x, y):
    self.w += np.array(x) * y
    self.b += y

  def fit(self, X, y):
    assert len(X[0]) == self.n, "Invalid input shape."
    for i in range(len(X)):
      self.__train(X[i], y[i])

  def predict(self, X):
    return np.sum(self.w * X, axis = 1) + self.b

## **OR GATE**

In [3]:
or_model = NeuralNet(2)

In [4]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [-1, 1, 1, 1]

In [5]:
or_model.fit(X, y)

In [6]:
or_model.w
or_model.b

2

In [7]:
or_model.predict(X)

array([-2.,  2.,  2.,  6.])

## **AND GATE**

In [8]:
and_model = NeuralNet(2)

In [9]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [-1, -1, -1, 1]

In [10]:
and_model.fit(X, y)

In [11]:
and_model.w
and_model.b

-2

In [12]:
and_model.predict(X)

array([-6., -2., -2.,  2.])

## **NOT GATE**

In [13]:
not_model = NeuralNet(1)

In [14]:
X = [
     [-1],
     [1]
]
y = [1, -1]

In [15]:
not_model.fit(X, y)

In [16]:
not_model.w, not_model.b

(array([-2.]), 0)

In [17]:
not_model.predict(X)

array([ 2., -2.])

## **NOR GATE**

In [18]:
nor_model = NeuralNet(2)

In [19]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [1, -1, -1, -1]

In [20]:
nor_model.fit(X, y)

In [21]:
nor_model.w, nor_model.b

(array([-2., -2.]), -2)

In [22]:
nor_model.predict(X)

array([ 2., -2., -2., -6.])

## **NAND GATE**

In [23]:
nand_model = NeuralNet(2)

In [24]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [1, 1, 1, -1]

In [25]:
nand_model.fit(X, y)

In [26]:
nand_model.w, nand_model.b

(array([-2., -2.]), 2)

In [27]:
nand_model.predict(X)

array([ 6.,  2.,  2., -2.])